<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useAppStore } from '../stores/app'

const store = useAppStore()
const router = useRouter()
const activeWatchFolders = computed(() => store.watchFolders.filter(folder => folder.enabled && folder.watching).length)
const artists = computed(() => new Set(store.files.map(file => file.artist).filter(Boolean)).size)
const albums = computed(() => new Set(store.files.map(file => file.album).filter(Boolean)).size)
const totalSize = computed(() => store.files.reduce((total, file) => total + (file.size || 0), 0))
const totalDuration = computed(() => store.files.reduce((total, file) => total + (file.duration || 0), 0))
const currentTasks = computed(() => store.tasks.filter(task => task.status === 'converting' || task.status === 'waiting'))
const completedTasks = computed(() => store.tasks.filter(task => task.status === 'success'))
const failedTasks = computed(() => store.tasks.filter(task => task.status === 'failed'))
const recentTasks = computed(() => [...store.tasks].sort((a, b) => (b.end_time || b.start_time || '').localeCompare(a.end_time || a.start_time || '')).slice(0, 5))
const formatBytes = (bytes: number) => bytes ? `${(bytes / 1024 / 1024).toFixed(bytes >= 1024 * 1024 * 1024 ? 2 : 0)}${bytes >= 1024 * 1024 * 1024 ? 'GB' : 'MB'}` : '0MB'
const formatDuration = (seconds: number) => `${String(Math.floor(seconds / 3600)).padStart(2, '0')}H${String(Math.floor(seconds % 3600 / 60)).padStart(2, '0')}m`
const fileName = (path: string) => path.replace(/\\/g, '/').split('/').pop() || '--'
const taskLabel = (status: string) => ({ waiting: '等待中', converting: '转换中', success: '已完成', failed: '失败', cancelled: '已取消', skipped: '已跳过' }[status] || status)
const taskType = (status: string) => ({ success: 'success', failed: 'danger', converting: 'primary', waiting: 'warning' }[status] || 'info') as 'success' | 'danger' | 'primary' | 'warning' | 'info'

onMounted(() => Promise.all([store.fetchFiles(), store.fetchTasks(), store.fetchProfiles(), store.fetchWatchFolders()]))
</script>

<template>
  <div class="dashboard">
    <section class="stat-grid">
      <button class="stat-card" @click="router.push('/files')"><span class="stat-mark purple">TR</span><small>全部歌曲</small><strong>{{ store.files.length }}</strong></button>
      <button class="stat-card" @click="router.push('/files')"><span class="stat-mark pink">LP</span><small>全部专辑</small><strong>{{ albums }}</strong></button>
      <button class="stat-card" @click="router.push('/files')"><span class="stat-mark purple">AR</span><small>全部艺术家</small><strong>{{ artists }}</strong></button>
      <button class="stat-card" @click="router.push('/files')"><span class="stat-mark neutral">GB</span><small>歌曲大小</small><strong>{{ formatBytes(totalSize) }}</strong></button>
      <button class="stat-card" @click="router.push('/tasks')"><span class="stat-mark pink">OK</span><small>任务完成率</small><strong>{{ store.tasks.length ? `${Math.round(completedTasks.length / store.tasks.length * 100)}%` : '0%' }}</strong></button>
      <button class="stat-card" @click="router.push('/tasks')"><span class="stat-mark neutral">TM</span><small>歌曲时长</small><strong class="duration">{{ formatDuration(totalDuration) }}</strong></button>
    </section>
    <section class="lower-grid">
      <article class="panel task-panel"><header><div><h2>转换任务概览</h2><p>实时查看队列及最近的处理结果</p></div><el-button link @click="router.push('/tasks')">查看全部 <el-icon><ArrowRight /></el-icon></el-button></header><div class="queue-summary"><div><span>进行中</span><strong>{{ currentTasks.length }}</strong></div><div><span>已完成</span><strong>{{ completedTasks.length }}</strong></div><div><span>需处理</span><strong class="warning">{{ failedTasks.length }}</strong></div></div><div v-if="recentTasks.length" class="task-list"><div v-for="task in recentTasks" :key="task.id" class="task-row"><div class="task-note"><el-icon><Headset /></el-icon></div><div><strong>{{ fileName(task.source_file) }}</strong><small>{{ task.output_file || '等待生成输出文件' }}</small></div><el-tag :type="taskType(task.status)" effect="light">{{ taskLabel(task.status) }}</el-tag></div></div><div v-else class="empty-state"><el-icon><Headset /></el-icon><strong>尚无转换任务</strong><span>从操作台选择音乐后即可开始。</span></div></article>
      <article class="panel monitor-panel"><header><div><h2>运行状态</h2><p>本地服务与自动化目录</p></div><el-button link @click="router.push('/watch-folders')">管理 <el-icon><ArrowRight /></el-icon></el-button></header><div class="monitor-main"><span class="pulse"><el-icon><Connection /></el-icon></span><div><strong>本地服务正常</strong><p>{{ activeWatchFolders }} / {{ store.watchFolders.length }} 个监控目录正在工作</p></div></div><div class="monitor-rows"><div><span>转换方案</span><strong>{{ store.profiles.length }} 个可用</strong></div><div><span>最近异常</span><strong :class="{ warning: failedTasks.length }">{{ failedTasks.length ? `${failedTasks.length} 个待处理` : '暂无异常' }}</strong></div></div></article>
    </section>
  </div>
</template>

<style scoped>
.dashboard { padding: 0; }.overview-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }.welcome-card, .panel, .stat-card { border: 0; background: #fff; box-shadow: 0 6px 18px rgb(32 36 48 / 7%); }.welcome-card { position: relative; display: flex; min-height: 242px; overflow: hidden; align-items: center; border-radius: 13px; padding: 34px 32px; }.welcome-copy { position: relative; z-index: 1; max-width: 55%; }.welcome-copy h1 { margin: 0 0 14px; color: #ef05ce; font-size: clamp(27px, 3vw, 40px); line-height: 1; letter-spacing: -1.5px; }.welcome-copy p { max-width: 345px; margin: 0 0 22px; color: #667084; font-size: 15px; line-height: 1.65; }.welcome-copy .el-button { border: 0; border-radius: 8px; background: #3920ee; }.welcome-card img { position: absolute; right: -13px; bottom: -6px; width: 61%; max-height: 100%; object-fit: contain; object-position: right bottom; }
.stat-grid { display: grid; grid-template-columns: repeat(3, 1fr); overflow: hidden; border-radius: 13px; background: #fff; box-shadow: 0 6px 18px rgb(32 36 48 / 7%); }.stat-card { position: relative; min-height: 121px; padding: 20px 22px; border-right: 1px solid #edf0f5; border-bottom: 1px solid #edf0f5; text-align: left; cursor: pointer; transition: background .2s, transform .2s; }.stat-card:nth-child(3n) { border-right: 0; }.stat-card:nth-child(n+4) { border-bottom: 0; }.stat-card:hover { background: #faf9ff; transform: translateY(-1px); }.stat-card span, .stat-card small { display: block; color: #70798a; font-size: 13px; }.stat-card strong { display: block; margin: 9px 0 3px; color: #222b3a; font-size: 32px; line-height: 1; letter-spacing: -1.1px; }.stat-card strong.purple { color: #4821f2; }.stat-card strong.pink { color: #ef05c9; }.stat-card small { font-size: 11px; }.stat-card .el-icon { position: absolute; top: 43px; right: 22px; color: #4c22f3; font-size: 24px; }.stat-card:nth-child(2) .el-icon, .stat-card:nth-child(4) .el-icon { color: #ed0dcc; }
.lower-grid { display: grid; grid-template-columns: minmax(0, 1.75fr) minmax(300px, .7fr); gap: 16px; margin-top: 16px; }.panel { min-height: 326px; border-radius: 13px; overflow: hidden; }.panel header { display: flex; align-items: center; justify-content: space-between; padding: 24px 28px 17px; }.panel h2 { margin: 0 0 5px; color: #202735; font-size: 17px; }.panel header p { margin: 0; color: #81899a; font-size: 12px; }.panel header .el-button { color: #3920ee; }.queue-summary { display: grid; grid-template-columns: repeat(3, 1fr); margin: 0 28px 14px; border-radius: 9px; background: #f8f7ff; }.queue-summary div { display: flex; min-height: 64px; flex-direction: column; align-items: center; justify-content: center; border-right: 1px solid #ebe9fa; }.queue-summary div:last-child { border-right: 0; }.queue-summary span { color: #747c8d; font-size: 11px; }.queue-summary strong { margin-top: 4px; color: #4021ee; font-size: 21px; }.warning { color: #ed0dcc !important; }.task-list { padding: 0 28px; }.task-row { display: grid; grid-template-columns: 36px 1fr auto; gap: 10px; align-items: center; min-height: 51px; border-top: 1px solid #edf0f5; }.task-note { display: grid; width: 28px; height: 28px; place-items: center; border-radius: 8px; background: #f1edff; color: #4821f2; }.task-row > div:nth-child(2) { display: flex; min-width: 0; flex-direction: column; gap: 3px; }.task-row strong, .task-row small { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.task-row strong { color: #303846; font-size: 12px; }.task-row small { color: #9198a6; font-size: 10px; }.empty-state { display: flex; min-height: 205px; flex-direction: column; gap: 7px; align-items: center; justify-content: center; color: #858d9c; font-size: 12px; }.empty-state .el-icon { color: #5d33f3; font-size: 31px; }.empty-state strong { color: #3a4250; }
.monitor-main { display: flex; gap: 13px; align-items: center; margin: 4px 28px 20px; padding: 18px; border-radius: 10px; background: linear-gradient(135deg, #4020ed, #7e21f4); color: #fff; }.pulse { display: grid; width: 40px; height: 40px; place-items: center; border-radius: 50%; background: rgb(255 255 255 / 18%); font-size: 21px; }.monitor-main strong { font-size: 15px; }.monitor-main p { margin: 6px 0 0; color: #e5dcff; font-size: 11px; }.monitor-rows { padding: 0 28px; }.monitor-rows div { display: flex; justify-content: space-between; padding: 13px 0; border-bottom: 1px solid #edf0f5; color: #757d8e; font-size: 12px; }.monitor-rows strong { color: #364051; font-weight: 600; }
@media (max-width: 1050px) { .overview-grid, .lower-grid { grid-template-columns: 1fr; }.welcome-card { min-height: 230px; }.stat-grid { min-height: 242px; } }
@media (max-width: 620px) { .welcome-card { min-height: 238px; padding: 27px 22px; }.welcome-copy { max-width: 63%; }.welcome-copy p { font-size: 13px; }.welcome-card img { width: 65%; opacity: .7; }.stat-grid { grid-template-columns: repeat(2, 1fr); }.stat-card:nth-child(3n) { border-right: 1px solid #edf0f5; }.stat-card:nth-child(2n) { border-right: 0; }.stat-card:nth-child(3) { border-bottom: 1px solid #edf0f5; }.stat-card { min-height: 112px; padding: 17px; }.stat-card strong { font-size: 26px; }.stat-card .el-icon { top: 38px; right: 16px; }.panel header, .task-list { padding-right: 18px; padding-left: 18px; }.queue-summary, .monitor-main, .monitor-rows { margin-right: 18px; margin-left: 18px; padding-right: 0; padding-left: 0; }.monitor-main { padding: 16px; }.task-row { grid-template-columns: 32px 1fr auto; }.task-row small { max-width: 140px; } }

/* 首页主视觉以用户提供的截图为基准。 */
.overview-grid { display: block; }.welcome-card { min-height: 664px; align-items: stretch; border: 1px solid #edf0f4; border-radius: 30px; padding: 0; box-shadow: 0 18px 38px rgb(46 52 76 / 7%); }.welcome-copy { display: flex; z-index: 1; width: 56%; max-width: none; flex-direction: column; justify-content: center; padding: 80px 7%; }.eyebrow { margin-bottom: 14px; color: #aa84fb; font-size: 15px; font-weight: 800; }.welcome-copy h1 { margin-bottom: 24px; color: #20293a; font-size: clamp(54px, 5.4vw, 92px); line-height: .94; letter-spacing: -4px; }.welcome-copy p { max-width: 730px; margin-bottom: 28px; color: #768195; font-size: 17px; line-height: 1.8; }.now-playing { display: inline-flex; width: fit-content; gap: 9px; align-items: center; border: 0; border-radius: 999px; padding: 14px 22px; background: #a783fa; color: #fff; font-size: 15px; font-weight: 800; cursor: pointer; box-shadow: 0 10px 20px rgb(168 130 250 / 28%); }.now-playing span { color: #efe9ff; font-weight: 600; }.spotlight-card { position: absolute; top: 22px; right: 22px; bottom: 22px; display: flex; width: 42%; overflow: hidden; flex-direction: column; justify-content: flex-end; border-radius: 25px; background: #222334; }.spotlight-card img { position: absolute; inset: 0; width: 100%; max-height: none; opacity: 1; object-fit: cover; object-position: center; }.spotlight-card::after { position: absolute; inset: 48% 0 0; background: linear-gradient(transparent, rgb(24 24 39 / 91%)); content: ''; }.spotlight-card > div { position: relative; z-index: 1; display: flex; flex-direction: column; padding: 0 30px 30px; color: #fff; }.spotlight-card strong { font-size: 58px; line-height: .9; }.spotlight-card span { margin-top: 8px; color: #d5d1e4; font-size: 14px; font-weight: 700; }
.stat-grid { grid-template-columns: repeat(6, 1fr); gap: 16px; margin-top: 20px; overflow: visible; border-radius: 0; background: transparent; box-shadow: none; }.stat-card { min-height: 177px; padding: 22px; border: 1px solid #eef0f4 !important; border-radius: 22px; background: #fff; box-shadow: 0 10px 22px rgb(42 48 74 / 5%); }.stat-card:hover { background: #fff; box-shadow: 0 14px 26px rgb(92 72 154 / 13%); }.stat-card .stat-mark { display: grid; width: 45px; height: 45px; margin: 0 0 16px; place-items: center; border-radius: 15px; font-size: 12px; font-weight: 800; }.stat-mark.purple { background: #f0ecff; color: #9d7df4; }.stat-mark.pink { background: #fdf0ff; color: #e3a2f4; }.stat-mark.neutral { background: #f0f1f3; color: #667180; }.stat-card small { color: #6d7789; font-size: 14px; font-weight: 700; }.stat-card strong { margin: 7px 0 0; color: #20293a; font-size: clamp(28px, 2.8vw, 48px); line-height: 1; letter-spacing: -1.8px; }.stat-card strong.duration { color: #a783fa; font-size: clamp(26px, 2.5vw, 44px); }.stat-card .el-icon { display: none; }
.lower-grid { margin-top: 22px; }.panel { border-radius: 22px; }.panel header { padding: 25px 28px 17px; }
@media (max-width: 1180px) { .welcome-card { min-height: 520px; }.stat-grid { grid-template-columns: repeat(3, 1fr); }.spotlight-card { width: 44%; }.welcome-copy h1 { font-size: 58px; } }
@media (max-width: 720px) { .welcome-card { min-height: 560px; border-radius: 23px; }.welcome-copy { width: 100%; justify-content: flex-start; padding: 44px 28px; }.eyebrow { font-size: 13px; }.welcome-copy h1 { font-size: 48px; letter-spacing: -2.5px; }.welcome-copy p { max-width: 62%; font-size: 13px; }.spotlight-card { top: auto; right: 14px; bottom: 14px; width: 57%; height: 260px; border-radius: 20px; }.spotlight-card > div { padding: 0 18px 18px; }.spotlight-card strong { font-size: 38px; }.stat-grid { grid-template-columns: repeat(2, 1fr); gap: 12px; }.stat-card { min-height: 145px; padding: 17px; border-radius: 18px; }.stat-card .stat-mark { width: 38px; height: 38px; margin-bottom: 13px; border-radius: 13px; }.stat-card small { font-size: 12px; }.stat-card strong { font-size: 29px; }.lower-grid { margin-top: 14px; } }
</style>
